// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ3ACBt8H6a8F25PwVQtkkjAHkPzOEsl4',
    appId: '1:586810221096:web:0f1d6add42225db224cb1d',
    messagingSenderId: '586810221096',
    projectId: 'eventnotification-dde69',
    authDomain: 'eventnotification-dde69.firebaseapp.com',
    storageBucket: 'eventnotification-dde69.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAfc1KKSv5_oZl-mmwpH4kgjXDR0rPzQk',
    appId: '1:586810221096:android:411f03055dfb54cf24cb1d',
    messagingSenderId: '586810221096',
    projectId: 'eventnotification-dde69',
    storageBucket: 'eventnotification-dde69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8_bSSkDpEXyTQgLhSgdQok8h_gJvoc-I',
    appId: '1:586810221096:ios:195893e7a352f75b24cb1d',
    messagingSenderId: '586810221096',
    projectId: 'eventnotification-dde69',
    storageBucket: 'eventnotification-dde69.appspot.com',
    iosBundleId: 'com.example.notificaiton',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8_bSSkDpEXyTQgLhSgdQok8h_gJvoc-I',
    appId: '1:586810221096:ios:8973f65acdc80a3124cb1d',
    messagingSenderId: '586810221096',
    projectId: 'eventnotification-dde69',
    storageBucket: 'eventnotification-dde69.appspot.com',
    iosBundleId: 'com.example.notificaiton.RunnerTests',
  );
}
